//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.02.21 at 03:01:37 PM BDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://bd.ohedulalam/spring-boot-soap", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package ohedulalam.bd.spring_boot_soap;
